name: Deploy to Deta
on: push
env:
  DETA_ACCESS_TOKEN: ${{ secrets.DETA_TOKEN }} 
  DETA_NAME: ${{ secrets.DETA_NAME }} 
  DETA_PROJECT: ${{ secrets.DETA_PROJECT }}
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2 
      - uses: actions/setup-node@v3
        with:
          node-version: 14
      - run: npm ci
      - run: npm test
      - run: npm run build
      - run: |
          curl -fsSL https://get.deta.dev/cli.sh | sh
          export PATH="/home/runner/.deta/bin:$PATH"
          deta clone --name $DETA_NAME --project $DETA_PROJECT dist/tmp
          mv dist/tmp/.deta .
          rm -rf dist/tmp
          deta deploy
