name: Deploy to Deta
on: push

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2 
      - uses: actions/setup-node@v3
        with:
          node-version: 14
      - run: npm ci
      - run: npm test
      - run: npm build
      - uses: BogDAAAMN/deta-deploy-action@v1.0.1
        with:
          deta-access-token: ${{ secrets.DETA_TOKEN }} 
          deta-name: ${{ secrets.DETA_NAME }} 
          deta-project: ${{ secrets.DETA_PROJECT }} 
